name: "health-check-for-website"
description: "check if a website is up or not"
author: Mustafa Khan
branding:
  icon: check-circle
  color: 'blue'
inputs: 
  website_url:
    description: "the url of the website that you want to check"
    required: true
  version_name:
    description: "a version specific tagthat you want to search for in the given website"
    required: false
    default: none
  method:
    description: "the method that you want to use ( wget or curl ) default is curl"
    required: false
    default: curl
  timeout:
    description: "the time ( in seconds ) you want to run this action to try to reach the given website ( default is 300 )"
    require: false
    default: 300
  tag:
    description: "how to tag the image Default: latest"
    
# outputs:
#   output-result:
#     description: "results of health check"
#     value: ${{ steps.test.outputs.output-result }}

    
runs:
  env:
    TIMEOUT: ${{ inputs.timeout }}
    WEBSITE: ${{ inputs.website_url }}
    VERSION: ${{ inputs.version_name }}
    METHOD: ${{ inputs.method }}
  using: "composite"
  steps:
    - name: test
      run: |
        sudo chmod u+x $GITHUB_ACTION_PATH/test.sh
        timeout $TIMEOUT $GITHUB_ACTION_PATH/test.sh $WEBSITE $VERSION $METHOD
      shell: bash
