name: "health-check"
description: "check if a website is up or not"

inputs: 
  website_url:
    description: "the url of the website that you want to check"
    required: true
  version_name:
    description: "a version specific tagthat you want to search for in the given website"
    required: false
    default: none
  method:
    description: "the method that you want to use ( wget or curl ) default is curl"
    required: false
    default: curl
  tag:
    description: "how to tag the image Default: latest"
    
  runs:
    using: "composite"
    steps:
      - name: installing dependencies
        run: sudo apt-get install wget
        env: 
          WEBSITE_NAME: ${{ inputs.website_url }}
          VERSION_NAME: ${{ inputs.version_name }}
          METHOD: ${{ inputs.method }}
      - name: test
      - run: |
          sudo chmod u+x ./test.sh
          timeout 300 ./test.sh $WEBSITE_NAME $VERSION_NAME $METHOD
        shell: bash
outputs:
  output-result:
    description: "results of health check"
    value: ${{ steps.test.outputs.output-result }}
